update bin/aws supporting non-terminal output.

diff --git a/bin/aws b/bin/aws
--- a/bin/aws
+++ b/bin/aws
@@ -5,13 +5,22 @@ app_name=$(basename "$(dirname "$abspath")")
 
 profile="${app_name}-${STAGE:-dev}-deploy"
 
-bin=$(which -a aws | tail -n 2  | head -n 1)
+bin=$(which -a aws | tail -n +2  | head -n 1)
+
+if [ ! ${bin} ]; then
+    echo "command not found: aws"
+    exit 1
+fi
+
 cmd=""${bin}" --profile "${profile}" "$@""
 
 GRAY='\033[0;30m'
 NO_COLOR='\033[0m'
 
-echo "Profile: $profile"
-echo -e "${GRAY}$ "${cmd}"${NO_COLOR}"
+if [ -t 1 ]; then
+    echo "Profile: $profile"
+    echo -e "${GRAY}$ "${cmd}"${NO_COLOR}"
+    echo
+fi
 
 $cmd
